export const POST_LOADING = "POST_LOADING";
export const POST_FORM_SUBMIT = "POST_FORM_SUBMIT";
export const POST_FORM_HTTP_REQUEST = "POST_FORM_HTTP_REQUEST";
export const POST_ADD = "POST_ADD";
export const POST_GET_PAGINATED_LIST = "POST_GET_PAGINATED_LIST";
export const POST_DELETE = "POST_DELETE";
export const POST_PAGNIATION_UPDATE = "POST_PAGNIATION_UPDATE";
export const POST_SUCCESS_TOAST = "POST_SUCCESS_TOAST";
export const POST_GET = "POST_GET";
export const POST_LAYOUT_STYLE = "POST_LAYOUT_STYLE";
export const POST_UPDATE = "POST_UPDATE";
export const POST_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "POST_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


