export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_FORM_SUBMIT = "PRODUCT_FORM_SUBMIT";
export const PRODUCT_FORM_HTTP_REQUEST = "PRODUCT_FORM_HTTP_REQUEST";
export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCT_GET_PAGINATED_LIST = "PRODUCT_GET_PAGINATED_LIST";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_PAGNIATION_UPDATE = "PRODUCT_PAGNIATION_UPDATE";
export const PRODUCT_SUCCESS_TOAST = "PRODUCT_SUCCESS_TOAST";
export const PRODUCT_GET = "PRODUCT_GET";
export const PRODUCT_LAYOUT_STYLE = "PRODUCT_LAYOUT_STYLE";
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const PRODUCT_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "PRODUCT_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


