export const GALLERY_LOADING = "GALLERY_LOADING";
export const GALLERY_FORM_SUBMIT = "GALLERY_FORM_SUBMIT";
export const GALLERY_FORM_HTTP_REQUEST = "GALLERY_FORM_HTTP_REQUEST";
export const GALLERY_ADD = "GALLERY_ADD";
export const GALLERY_GET_PAGINATED_LIST = "GALLERY_GET_PAGINATED_LIST";
export const GALLERY_DELETE = "GALLERY_DELETE";
export const GALLERY_PAGNIATION_UPDATE = "GALLERY_PAGNIATION_UPDATE";
export const GALLERY_SUCCESS_TOAST = "GALLERY_SUCCESS_TOAST";
export const GALLERY_GET = "GALLERY_GET";
export const GALLERY_LAYOUT_STYLE = "GALLERY_LAYOUT_STYLE";
export const GALLERY_UPDATE = "GALLERY_UPDATE";
export const GALLERY_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "GALLERY_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


