export const POLICY_LOADING = "POLICY_LOADING";
export const POLICY_FORM_SUBMIT = "POLICY_FORM_SUBMIT";
export const POLICY_FORM_HTTP_REQUEST = "POLICY_FORM_HTTP_REQUEST";
export const POLICY_ADD = "POLICY_ADD";
export const POLICY_GET_PAGINATED_LIST = "POLICY_GET_PAGINATED_LIST";
export const POLICY_DELETE = "POLICY_DELETE";
export const POLICY_PAGNIATION_UPDATE = "POLICY_PAGNIATION_UPDATE";
export const POLICY_SUCCESS_TOAST = "POLICY_SUCCESS_TOAST";
export const POLICY_GET = "POLICY_GET";
export const POLICY_LAYOUT_STYLE = "POLICY_LAYOUT_STYLE";
export const POLICY_UPDATE = "POLICY_UPDATE";
export const POLICY_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "POLICY_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


