export const APPLICATION_ERROR_LOADING = "APPLICATION_ERROR_LOADING";
export const APPLICATION_ERROR_FORM_SUBMIT = "APPLICATION_ERROR_FORM_SUBMIT";
export const APPLICATION_ERROR_FORM_HTTP_REQUEST = "APPLICATION_ERROR_FORM_HTTP_REQUEST";
export const APPLICATION_ERROR_ADD = "APPLICATION_ERROR_ADD";
export const APPLICATION_ERROR_GET_PAGINATED_LIST = "APPLICATION_ERROR_GET_PAGINATED_LIST";
export const APPLICATION_ERROR_DELETE = "APPLICATION_ERROR_DELETE";
export const APPLICATION_ERROR_PAGNIATION_UPDATE = "APPLICATION_ERROR_PAGNIATION_UPDATE";
export const APPLICATION_ERROR_SUCCESS_TOAST = "APPLICATION_ERROR_SUCCESS_TOAST";
export const APPLICATION_ERROR_GET = "APPLICATION_ERROR_GET";
export const APPLICATION_ERROR_LAYOUT_STYLE = "APPLICATION_ERROR_LAYOUT_STYLE";
export const APPLICATION_ERROR_UPDATE = "APPLICATION_ERROR_UPDATE";
export const APPLICATION_ERROR_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "APPLICATION_ERROR_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


